namespace OnlineStore.Migrations
{
    using OnlineStore.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<OnlineStore.Models.OnlineStoreEntities>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
            ContextKey = "OnlineStore.Models.OnlineStoreEntities";
        }

        protected override void Seed(OnlineStore.Models.OnlineStoreEntities context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.

            List<Category> Categories = new List<Category>
            {
                new Category { Name = "Rock" },
                new Category { Name = "Jazz" },
                new Category { Name = "Metal" },
                new Category { Name = "Alternative" },
                new Category { Name = "Disco" },
                new Category { Name = "Blues" },
                new Category { Name = "Latin" },
                new Category { Name = "Reggae" },
                new Category { Name = "Pop" },
                new Category { Name = "Classical" }
            };

            List<Brand> Brands = new List<Brand>
            {
                new Brand { Name = "Aaron Copland & London Symphony Orchestra" },
                new Brand { Name = "Aaron Goldberg" },
                new Brand { Name = "AC/DC" },
                new Brand { Name = "Accept" },
                new Brand { Name = "Adrian Leaper & Doreen de Feis" },
                new Brand { Name = "Aerosmith" },
                new Brand { Name = "Aisha Duo" },
                new Brand { Name = "Alanis Morissette" },
                new Brand { Name = "Alberto Turco & Nova Schola Gregoriana" },
                new Brand { Name = "Alice In Chains" },
                new Brand { Name = "Amy Winehouse" },
                new Brand { Name = "Anita Ward" },
                new Brand { Name = "Antônio Carlos Jobim" },
                new Brand { Name = "Apocalyptica" },
                new Brand { Name = "Audioslave" },
                new Brand { Name = "Barry Wordsworth & BBC Concert Orchestra" },
                new Brand { Name = "Berliner Philharmoniker & Hans Rosbaud" },
                new Brand { Name = "Berliner Philharmoniker & Herbert Von Karajan" },
                new Brand { Name = "Billy Cobham" },
                new Brand { Name = "Black Label Society" },
                new Brand { Name = "Black Sabbath" },
                new Brand { Name = "Boston Symphony Orchestra & Seiji Ozawa" },
                new Brand { Name = "Britten Sinfonia, Ivor Bolton & Lesley Garrett" },
                new Brand { Name = "Bruce Dickinson" },
                new Brand { Name = "Buddy Guy" },
                new Brand { Name = "Caetano Veloso" },
                new Brand { Name = "Cake" },
                new Brand { Name = "Calexico" },
                new Brand { Name = "Cássia Eller" },
                new Brand { Name = "Chic" },
                new Brand { Name = "Chicago Symphony Orchestra & Fritz Reiner" },
                new Brand { Name = "Chico Buarque" },
                new Brand { Name = "Chico Science & Nação Zumbi" },
                new Brand { Name = "Choir Of Westminster Abbey & Simon Preston" },
                new Brand { Name = "Chris Cornell" },
                new Brand { Name = "Christopher O'Riley" },
                new Brand { Name = "Cidade Negra" },
                new Brand { Name = "Cláudio Zoli" },
                new Brand { Name = "Creedence Clearwater Revival" },
                new Brand { Name = "David Coverdale" },
                new Brand { Name = "Deep Purple" },
                new Brand { Name = "Dennis Chambers" },
                new Brand { Name = "Djavan" },
                new Brand { Name = "Donna Summer" },
                new Brand { Name = "Dread Zeppelin" },
                new Brand { Name = "Ed Motta" },
                new Brand { Name = "Edo de Waart & San Francisco Symphony" },
                new Brand { Name = "Elis Regina" },
                new Brand { Name = "English Concert & Trevor Pinnock" },
                new Brand { Name = "Eric Clapton" },
                new Brand { Name = "Eugene Ormandy" },
                new Brand { Name = "Faith No More" },
                new Brand { Name = "Falamansa" },
                new Brand { Name = "Foo Fighters" },
                new Brand { Name = "Frank Zappa & Captain Beefheart" },
                new Brand { Name = "Fretwork" },
                new Brand { Name = "Funk Como Le Gusta" },
                new Brand { Name = "Gerald Moore" },
                new Brand { Name = "Gilberto Gil" },
                new Brand { Name = "Godsmack" },
                new Brand { Name = "Gonzaguinha" },
                new Brand { Name = "Göteborgs Symfoniker & Neeme Järvi" },
                new Brand { Name = "Guns N' Roses" },
                new Brand { Name = "Gustav Mahler" },
                new Brand { Name = "Incognito" },
                new Brand { Name = "Iron Maiden" },
                new Brand { Name = "James Levine" },
                new Brand { Name = "Jamiroquai" },
                new Brand { Name = "Jimi Hendrix" },
                new Brand { Name = "Joe Satriani" },
                new Brand { Name = "Jorge Ben" },
                new Brand { Name = "Jota Quest" },
                new Brand { Name = "Judas Priest" },
                new Brand { Name = "Julian Bream" },
                new Brand { Name = "Kent Nagano and Orchestre de l'Opéra de Lyon" },
                new Brand { Name = "Kiss" },
                new Brand { Name = "Led Zeppelin" },
                new Brand { Name = "Legião Urbana" },
                new Brand { Name = "Lenny Kravitz" },
                new Brand { Name = "Les Arts Florissants & William Christie" },
                new Brand { Name = "London Symphony Orchestra & Sir Charles Mackerras" },
                new Brand { Name = "Luciana Souza/Romero Lubambo" },
                new Brand { Name = "Lulu Santos" },
                new Brand { Name = "Marcos Valle" },
                new Brand { Name = "Marillion" },
                new Brand { Name = "Marisa Monte" },
                new Brand { Name = "Martin Roscoe" },
                new Brand { Name = "Maurizio Pollini" },
                new Brand { Name = "Mela Tenenbaum, Pro Musica Prague & Richard Kapp" },
                new Brand { Name = "Men At Work" },
                new Brand { Name = "Metallica" },
                new Brand { Name = "Michael Tilson Thomas & San Francisco Symphony" },
                new Brand { Name = "Miles Davis" },
                new Brand { Name = "Milton Nascimento" },
                new Brand { Name = "Mötley Crüe" },
                new Brand { Name = "Motörhead" },
                new Brand { Name = "Nash Ensemble" },
                new Brand { Name = "Nicolaus Esterhazy Sinfonia" },
                new Brand { Name = "Nirvana" },
                new Brand { Name = "O Terço" },
                new Brand { Name = "Olodum" },
                new Brand { Name = "Orchestra of The Age of Enlightenment" },
                new Brand { Name = "Os Paralamas Do Sucesso" },
                new Brand { Name = "Ozzy Osbourne" },
                new Brand { Name = "Page & Plant" },
                new Brand { Name = "Paul D'Ianno" },
                new Brand { Name = "Pearl Jam" },
                new Brand { Name = "Pink Floyd" },
                new Brand { Name = "Queen" },
                new Brand { Name = "R.E.M." },
                new Brand { Name = "Raul Seixas" },
                new Brand { Name = "Red Hot Chili Peppers" },
                new Brand { Name = "Roger Norrington, London Classical Players" },
                new Brand { Name = "Royal Philharmonic Orchestra & Sir Thomas Beecham" },
                new Brand { Name = "Rush" },
                new Brand { Name = "Santana" },
                new Brand { Name = "Scholars Baroque Ensemble" },
                new Brand { Name = "Scorpions" },
                new Brand { Name = "Sergei Prokofiev & Yuri Temirkanov" },
                new Brand { Name = "Sir Georg Solti & Wiener Philharmoniker" },
                new Brand { Name = "Skank" },
                new Brand { Name = "Soundgarden" },
                new Brand { Name = "Spyro Gyra" },
                new Brand { Name = "Stevie Ray Vaughan & Double Trouble" },
                new Brand { Name = "Stone Temple Pilots" },
                new Brand { Name = "System Of A Down" },
                new Brand { Name = "Temple of the Dog" },
                new Brand { Name = "Terry Bozzio, Tony Levin & Steve Stevens" },
                new Brand { Name = "The 12 Cellists of The Berlin Philharmonic" },
                new Brand { Name = "The Black Crowes" },
                new Brand { Name = "The Cult" },
                new Brand { Name = "The Doors" },
                new Brand { Name = "The King's Singers" },
                new Brand { Name = "The Police" },
                new Brand { Name = "The Posies" },
                new Brand { Name = "The Rolling Stones" },
                new Brand { Name = "The Who" },
                new Brand { Name = "Tim Maia" },
                new Brand { Name = "Ton Koopman" },
                new Brand { Name = "U2" },
                new Brand { Name = "UB40" },
                new Brand { Name = "Van Halen" },
                new Brand { Name = "Various Brands" },
                new Brand { Name = "Velvet Revolver" },
                new Brand { Name = "Vinícius De Moraes" },
                new Brand { Name = "Wilhelm Kempff" },
                new Brand { Name = "Yehudi Menuhin" },
                new Brand { Name = "Yo-Yo Ma" },
                new Brand { Name = "Zeca Pagodinho" }
            };

            new List<Product>
            {
                new Product { Name = "A Copland Celebration, Vol. I", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Aaron Copland & London Symphony Orchestra"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Worlds", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Aaron Goldberg"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "For Those About To Rock We Salute You", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "AC/DC"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Let There Be Rock", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "AC/DC"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Balls to the Wall", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Accept"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Restless and Wild", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Accept"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Górecki: Symphony No. 3", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Adrian Leaper & Doreen de Feis"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Big Ones", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Aerosmith"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Quiet Songs", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Aisha Duo"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Jagged Little Pill", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Alanis Morissette"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Facelift", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Alice In Chains"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Frank", Category = Categories.Single(g => g.Name == "Pop"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Amy Winehouse"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ring My Bell", Category = Categories.Single(g => g.Name == "Disco"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Anita Ward"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chill: Brazil (Disc 2)", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Antônio Carlos Jobim"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Warner 25 Anos", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Antônio Carlos Jobim"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Plays Metallica By Four Cellos", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Apocalyptica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Revelations", Category = Categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Audioslave"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Audioslave", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Audioslave"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Last Night of the Proms", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Barry Wordsworth & BBC Concert Orchestra"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Sibelius: Finlandia", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Berliner Philharmoniker & Hans Rosbaud"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mozart: Symphonies Nos. 40 & 41", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Berliner Philharmoniker & Herbert Von Karajan"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best Of Billy Cobham", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Billy Cobham"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Alcohol Fueled Brewtality Live! [Disc 1]", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Black Label Society"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Alcohol Fueled Brewtality Live! [Disc 2]", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Black Label Society"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Black Sabbath Vol. 4 (Remaster)", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Black Sabbath"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Black Sabbath", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Black Sabbath"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Carmina Burana", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Boston Symphony Orchestra & Seiji Ozawa"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "A Soprano Inspired", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Britten Sinfonia, Ivor Bolton & Lesley Garrett"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chemical Wedding", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Bruce Dickinson"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Prenda Minha", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Caetano Veloso"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Sozinho Remix Ao Vivo", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Caetano Veloso"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Cake: B-Sides and Rarities", Category = Categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Cake"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Carried to Dust (Bonus Track Version)", Category = Categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Calexico"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Cássia Eller - Sem Limite [Disc 1]", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Cássia Eller"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Le Freak", Category = Categories.Single(g => g.Name == "Disco"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Chic"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Scheherazade", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Chicago Symphony Orchestra & Fritz Reiner"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Minha Historia", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Chico Buarque"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Afrociberdelia", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Chico Science & Nação Zumbi"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Da Lama Ao Caos", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Chico Science & Nação Zumbi"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Carry On", Category = Categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Chris Cornell"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "SCRIABIN: Vers la flamme", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Christopher O'Riley"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Acústico MTV [Live]", Category = Categories.Single(g => g.Name == "Reggae"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Cidade Negra"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Cidade Negra - Hits", Category = Categories.Single(g => g.Name == "Reggae"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Cidade Negra"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Na Pista", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Cláudio Zoli"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chronicle, Vol. 1", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Creedence Clearwater Revival"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chronicle, Vol. 2", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Creedence Clearwater Revival"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Into The Light", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "David Coverdale"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Come Taste The Band", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Deep Purple In Rock", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Fireball", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Machine Head", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "MK III The Final Concerts [Disc 1]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Purpendicular", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Slaves And Masters", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Stormbringer", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Battle Rages On", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Final Concerts (Disc 2)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Deep Purple"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Outbreak", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Dennis Chambers"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Djavan Ao Vivo - Vol. 02", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Djavan"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Djavan Ao Vivo - Vol. 1", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Djavan"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "MacArthur Park Suite", Category = Categories.Single(g => g.Name == "Disco"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Donna Summer"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Un-Led-Ed", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Dread Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best of Ed Motta", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Ed Motta"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Adams, John: The Chairman Dances", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Edo de Waart & San Francisco Symphony"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Elis Regina-Minha História", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Elis Regina"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Pachelbel: Canon & Gigue", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "English Concert & Trevor Pinnock"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Unplugged", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Eric Clapton"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Cream Of Clapton", Category = Categories.Single(g => g.Name == "Blues"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Eric Clapton"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Unplugged", Category = Categories.Single(g => g.Name == "Blues"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Eric Clapton"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Respighi:Pines of Rome", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Eugene Ormandy"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Strauss: Waltzes", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Eugene Ormandy"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "King For A Day Fool For A Lifetime", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Faith No More"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Deixa Entrar", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Falamansa"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "In Your Honor [Disc 1]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Foo Fighters"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "In Your Honor [Disc 2]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Foo Fighters"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Colour And The Shape", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Foo Fighters"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bongo Fury", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Frank Zappa & Captain Beefheart"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Roda De Funk", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Funk Como Le Gusta"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Quanta Gente Veio Ver (Live)", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Gilberto Gil"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Quanta Gente Veio ver--Bônus De Carnaval", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Gilberto Gil"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Faceless", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Godsmack"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Meus Momentos", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Gonzaguinha"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Nielsen: The Six Symphonies", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Göteborgs Symfoniker & Neeme Järvi"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Appetite for Destruction", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Guns N' Roses"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Use Your Illusion I", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Guns N' Roses"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Use Your Illusion II", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Guns N' Roses"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Blue Moods", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Incognito"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "A Matter of Life and Death", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Brave New World", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Fear Of The Dark", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live At Donington 1992 (Disc 1)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live At Donington 1992 (Disc 2)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Rock In Rio [CD2]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Number of The Beast", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The X Factor", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Virtual XI", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "A Real Dead One", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "A Real Live One", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live After Death", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "No Prayer For The Dying", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Piece Of Mind", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Powerslave", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Rock In Rio [CD1]", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Rock In Rio [CD2]", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Seventh Son of a Seventh Son", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Somewhere in Time", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Number of The Beast", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Iron Maiden", Category = Categories.Single(g => g.Name == "Blues"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Iron Maiden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mascagni: Cavalleria Rusticana", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "James Levine"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Emergency On Planet Earth", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Jamiroquai"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Are You Experienced?", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Jimi Hendrix"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Surfing with the Alien (Remastered)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Joe Satriani"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Jorge Ben Jor 25 Anos", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Jorge Ben"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Jota Quest-1995", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Jota Quest"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Living After Midnight", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Judas Priest"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Weill: The Seven Deadly Sins", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Kent Nagano and Orchestre de l'Opéra de Lyon"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Kiss", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Kiss"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Unplugged [Live]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Kiss"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "BBC Sessions [Disc 1] [Live]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "BBC Sessions [Disc 2] [Live]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Coda", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Houses Of The Holy", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "In Through The Out Door", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "IV", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Led Zeppelin I", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Led Zeppelin II", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Led Zeppelin III", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Physical Graffiti [Disc 1]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Physical Graffiti [Disc 2]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Presence", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Song Remains The Same (Disc 1)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Song Remains The Same (Disc 2)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Led Zeppelin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mais Do Mesmo", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Legião Urbana"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits", Category = Categories.Single(g => g.Name == "Reggae"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Lenny Kravitz"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Lenny Kravitz"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Lenny Kravitz"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Tchaikovsky: The Nutcracker", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "London Symphony Orchestra & Sir Charles Mackerras"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Duos II", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Luciana Souza/Romero Lubambo"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Chill: Brazil (Disc 1)", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Marcos Valle"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Misplaced Childhood", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Marillion"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Barulhinho Bom", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Marisa Monte"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Szymanowski: Piano Works, Vol. 1", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Martin Roscoe"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best Of Men At Work", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Men At Work"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "...And Justice For All", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Metallica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Black Product", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Metallica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Garage Inc. (Disc 1)", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Metallica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Garage Inc. (Disc 2)", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Metallica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Load", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Metallica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Master Of Puppets", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Metallica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "ReLoad", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Metallica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ride The Lightning", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Metallica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "St. Anger", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Metallica"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Berlioz: Symphonie Fantastique", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Prokofiev: Romeo & Juliet", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Michael Tilson Thomas & San Francisco Symphony"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Miles Ahead", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Miles Davis"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Essential Miles Davis [Disc 1]", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Miles Davis"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Essential Miles Davis [Disc 2]", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Miles Davis"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Milton Nascimento Ao Vivo", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Milton Nascimento"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Minas", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Milton Nascimento"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Motley Crue Greatest Hits", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Mötley Crüe"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ace Of Spades", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Motörhead"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mozart: Chamber Music", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Nash Ensemble"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best of Beethoven", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Nicolaus Esterhazy Sinfonia"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Nevermind", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Nirvana"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Compositores", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "O Terço"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Olodum", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Olodum"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bach: The Brandenburg Concertos", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Orchestra of The Age of Enlightenment"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Acústico MTV", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Os Paralamas Do Sucesso"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Arquivo II", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Os Paralamas Do Sucesso"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Arquivo Os Paralamas Do Sucesso", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Os Paralamas Do Sucesso"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Tribute", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Ozzy Osbourne"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bark at the Moon (Remastered)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Ozzy Osbourne"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Blizzard of Ozz", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Ozzy Osbourne"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Diary of a Madman (Remastered)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Ozzy Osbourne"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "No More Tears (Remastered)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Ozzy Osbourne"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Speak of the Devil", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Ozzy Osbourne"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Walking Into Clarksdale", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Page & Plant"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Beast Live", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Paul D'Ianno"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live On Two Legs [Live]", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Pearl Jam"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Riot Act", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Pearl Jam"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ten", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Pearl Jam"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Vs.", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Pearl Jam"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Dark Side Of The Moon", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Pink Floyd"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits I", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Queen"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Greatest Hits II", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Queen"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "News Of The World", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Queen"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "New Adventures In Hi-Fi", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "R.E.M."), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Raul Seixas", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Raul Seixas"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "By The Way", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Red Hot Chili Peppers"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Californication", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Red Hot Chili Peppers"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Purcell: The Fairy Queen", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Roger Norrington, London Classical Players"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Haydn: Symphonies 99 - 104", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Royal Philharmonic Orchestra & Sir Thomas Beecham"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Retrospective I (1974-1980)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Rush"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Santana - As Years Go By", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Santana"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Santana Live", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Santana"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Supernatural", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Santana"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Handel: The Messiah (Highlights)", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Scholars Baroque Ensemble"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Prokofiev: Symphony No.1", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Sergei Prokofiev & Yuri Temirkanov"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Wagner: Favourite Overtures", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Sir Georg Solti & Wiener Philharmoniker"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Maquinarama", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Skank"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "O Samba Pocon", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Skank"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "A-Sides", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Soundgarden"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Heart of the Night", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Spyro Gyra"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Morning Dance", Category = Categories.Single(g => g.Name == "Jazz"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Spyro Gyra"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "In Step", Category = Categories.Single(g => g.Name == "Blues"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Stevie Ray Vaughan & Double Trouble"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Core", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Stone Temple Pilots"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Mezmerize", Category = Categories.Single(g => g.Name == "Metal"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "System Of A Down"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Temple of the Dog", Category = Categories.Single(g => g.Name == "Alternative"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Temple of the Dog"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "[1997] Black Light Syndrome", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Terry Bozzio, Tony Levin & Steve Stevens"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "South American Getaway", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The 12 Cellists of The Berlin Philharmonic"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live [Disc 1]", Category = Categories.Single(g => g.Name == "Blues"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Black Crowes"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Live [Disc 2]", Category = Categories.Single(g => g.Name == "Blues"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Black Crowes"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Beyond Good And Evil", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Cult"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Doors", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Doors"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "English Renaissance", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The King's Singers"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Police Greatest Hits", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Police"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Every Kind of Light", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Posies"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Hot Rocks, 1964-1971 (Disc 1)", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Rolling Stones"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "No Security", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Rolling Stones"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Voodoo Lounge", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Rolling Stones"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "My Generation - The Very Best Of The Who", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "The Who"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Serie Sem Limite (Disc 1)", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Tim Maia"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Serie Sem Limite (Disc 2)", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Tim Maia"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bach: Toccata & Fugue in D Minor", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Ton Koopman"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Achtung Baby", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "U2"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "B-Sides 1980-1990", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "U2"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "How To Dismantle An Atomic Bomb", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "U2"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Pop", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "U2"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Rattle And Hum", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "U2"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best Of 1980-1990", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "U2"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "War", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "U2"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Zooropa", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "U2"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "UB40 The Best Of - Volume Two [UK]", Category = Categories.Single(g => g.Name == "Reggae"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "UB40"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Diver Down", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Van Halen"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "The Best Of Van Halen, Vol. I", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Van Halen"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Van Halen III", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Van Halen"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Van Halen", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Van Halen"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ax?Bahia 2001", Category = Categories.Single(g => g.Name == "Pop"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Various Brands"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Sambas De Enredo 2001", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Various Brands"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Vozes do MPB", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Various Brands"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Contraband", Category = Categories.Single(g => g.Name == "Rock"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Velvet Revolver"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Vinicius De Moraes", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Vinícius De Moraes"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bach: Goldberg Variations", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Wilhelm Kempff"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bartok: Violin & Viola Concertos", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Yehudi Menuhin"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Bach: The Cello Suites", Category = Categories.Single(g => g.Name == "Classical"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Yo-Yo Ma"), ImageUrl = "/Content/Images/placeholder.gif" },
                new Product { Name = "Ao Vivo [IMPORT]", Category = Categories.Single(g => g.Name == "Latin"), Price = 8.99M, Brand = Brands.Single(a => a.Name == "Zeca Pagodinho"), ImageUrl = "/Content/Images/placeholder.gif" },
            }.ForEach(a => context.Products.AddOrUpdate(a));
        }
    }
}
